import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  await knex('packages').del();

  await knex('packages').insert([
    {
      id: uuidv4(),
      name: 'Gói Basic',
      slug: 'goi-basic',
      description: 'Gói cơ bản cho tiệc cưới ấm cúng',
      price: 50000000,
      features: JSON.stringify([
        'Trang trí sảnh tiệc cơ bản',
        'Backdrop chụp ảnh đơn giản',
        'Âm thanh ánh sáng cơ bản',
        'MC dẫn chương trình',
        'Hỗ trợ setup và dọn dẹp',
        'Tư vấn kế hoạch cơ bản',
      ]),
      is_popular: false,
      is_active: true,
    },
    {
      id: uuidv4(),
      name: 'Gói Standard',
      slug: 'goi-standard',
      description: 'Gói tiêu chuẩn với đầy đủ tiện nghi',
      price: 80000000,
      features: JSON.stringify([
        'Trang trí sảnh tiệc cao cấp',
        'Backdrop chụp ảnh đẹp mắt',
        'Hệ thống âm thanh ánh sáng hiện đại',
        'MC chuyên nghiệp',
        'Makeup artist cho cô dâu',
        'Chụp ảnh cưới (100 ảnh)',
        'Album ảnh cưới',
        'Hỗ trợ setup và dọn dẹp',
        'Tư vấn kế hoạch chi tiết',
      ]),
      is_popular: true,
      is_active: true,
    },
    {
      id: uuidv4(),
      name: 'Gói Premium',
      slug: 'goi-premium',
      description: 'Gói Premium mang đến trải nghiệm đám cưới hoàn hảo với đầy đủ các dịch vụ cao cấp. Từ trang trí sang trọng, chụp ảnh quay phim chuyên nghiệp đến wedding planner tận tâm, chúng tôi đảm bảo mọi khoảnh khắc đều trọn vẹn.',
      price: 100000000,
      features: JSON.stringify([
        'Trang trí sảnh tiệc sang trọng',
        'Chụp ảnh quay phim chuyên nghiệp',
        'Wedding planner tận tâm',
        'Hệ thống âm thanh ánh sáng cao cấp',
        'MC dẫn chương trình chuyên nghiệp',
        'Makeup artist + Hair stylist',
        'Backdrop 3D cao cấp',
        'Album ảnh + Video highlights',
        'Bánh cưới 3 tầng',
        'Hoa tươi cao cấp',
        'Hỗ trợ setup và dọn dẹp',
        'Tư vấn kế hoạch chi tiết',
      ]),
      is_popular: true,
      is_active: true,
    },
    {
      id: uuidv4(),
      name: 'Gói Luxury',
      slug: 'goi-luxury',
      description: 'Gói xa hoa đẳng cấp 5 sao',
      price: 200000000,
      features: JSON.stringify([
        'Trang trí sảnh tiệc đẳng cấp 5 sao',
        'Backdrop pha lê + LED mapping',
        'Hệ thống âm thanh ánh sáng đẳng cấp',
        'MC + Ban nhạc + DJ',
        'Makeup artist + Hair stylist VIP',
        'Chụp ảnh cưới không giới hạn',
        'Quay phim 4K + Flycam',
        'Album ảnh cao cấp + Video cinematic',
        'Bánh cưới 5 tầng thiết kế độc đáo',
        'Hoa tươi nhập khẩu',
        'Wedding planner chuyên nghiệp',
        'Xe hoa sang trọng',
        'Phục vụ rượu champagne',
        'Pháo hoa nghệ thuật',
        'Hỗ trợ setup và dọn dẹp',
      ]),
      is_popular: false,
      is_active: true,
    },
  ]);
}
