import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('galleries').del();

  const now = new Date();

  // Get product IDs from products table
  const products = await knex('products').select('id', 'slug');
  const productMap: { [key: string]: string } = {};
  products.forEach((p: any) => {
    productMap[p.slug] = p.id;
  });

  // Insert seed entries for product galleries
  const galleries = [
    // Nhẫn cưới vàng 18K đính kim cương
    {
      id: uuidv4(),
      title: 'Nhẫn cưới vàng 18K - Ảnh chính',
      alt_text: 'Nhẫn cưới vàng 18K đính kim cương thiên nhiên',
      file_name: 'nhan-cuoi-vang-18k-1.jpg',
      file_path: '/uploads/products/nhan-cuoi-vang-18k-1.jpg',
      file_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
      mime_type: 'image/jpeg',
      file_size: 245678,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-cuoi-vang-18k-dinh-kim-cuong'],
      related_type: 'product',
      display_order: 0,
      is_primary: true,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Nhẫn cưới vàng 18K - Chi tiết kim cương',
      alt_text: 'Chi tiết kim cương trên nhẫn cưới',
      file_name: 'nhan-cuoi-vang-18k-2.jpg',
      file_path: '/uploads/products/nhan-cuoi-vang-18k-2.jpg',
      file_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
      mime_type: 'image/jpeg',
      file_size: 198234,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-cuoi-vang-18k-dinh-kim-cuong'],
      related_type: 'product',
      display_order: 1,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Nhẫn cưới vàng 18K - Góc nghiêng',
      alt_text: 'Nhẫn cưới vàng 18K góc nghiêng',
      file_name: 'nhan-cuoi-vang-18k-3.jpg',
      file_path: '/uploads/products/nhan-cuoi-vang-18k-3.jpg',
      file_url: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800',
      mime_type: 'image/jpeg',
      file_size: 223456,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-cuoi-vang-18k-dinh-kim-cuong'],
      related_type: 'product',
      display_order: 2,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },

    // Nhẫn cưới vàng trắng 18K
    {
      id: uuidv4(),
      title: 'Nhẫn cưới vàng trắng 18K - Ảnh chính',
      alt_text: 'Nhẫn cưới vàng trắng 18K thiết kế hiện đại',
      file_name: 'nhan-cuoi-vang-trang-1.jpg',
      file_path: '/uploads/products/nhan-cuoi-vang-trang-1.jpg',
      file_url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
      mime_type: 'image/jpeg',
      file_size: 187654,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-cuoi-vang-trang-18k'],
      related_type: 'product',
      display_order: 0,
      is_primary: true,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Nhẫn cưới vàng trắng 18K - Chi tiết',
      alt_text: 'Chi tiết bề mặt nhẫn vàng trắng',
      file_name: 'nhan-cuoi-vang-trang-2.jpg',
      file_path: '/uploads/products/nhan-cuoi-vang-trang-2.jpg',
      file_url: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800',
      mime_type: 'image/jpeg',
      file_size: 201234,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-cuoi-vang-trang-18k'],
      related_type: 'product',
      display_order: 1,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },

    // Dây chuyền vàng 24K
    {
      id: uuidv4(),
      title: 'Dây chuyền vàng 24K - Ảnh chính',
      alt_text: 'Dây chuyền vàng 24K nguyên chất',
      file_name: 'day-chuyen-vang-24k-1.jpg',
      file_path: '/uploads/products/day-chuyen-vang-24k-1.jpg',
      file_url: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800',
      mime_type: 'image/jpeg',
      file_size: 312456,
      width: 800,
      height: 1000,
      category: 'product',
      related_id: productMap['day-chuyen-vang-24k'],
      related_type: 'product',
      display_order: 0,
      is_primary: true,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Dây chuyền vàng 24K - Chi tiết mắt xích',
      alt_text: 'Chi tiết mắt xích dây chuyền vàng',
      file_name: 'day-chuyen-vang-24k-2.jpg',
      file_path: '/uploads/products/day-chuyen-vang-24k-2.jpg',
      file_url: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800',
      mime_type: 'image/jpeg',
      file_size: 267890,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['day-chuyen-vang-24k'],
      related_type: 'product',
      display_order: 1,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },

    // Vòng tay bạc 925
    {
      id: uuidv4(),
      title: 'Vòng tay bạc 925 - Ảnh chính',
      alt_text: 'Vòng tay bạc 925 cao cấp',
      file_name: 'vong-tay-bac-925-1.jpg',
      file_path: '/uploads/products/vong-tay-bac-925-1.jpg',
      file_url: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800',
      mime_type: 'image/jpeg',
      file_size: 156789,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['vong-tay-bac-925'],
      related_type: 'product',
      display_order: 0,
      is_primary: true,
      is_active: true,
      created_at: now,
      updated_at: now,
    },

    // Nhẫn kim cương 1 carat
    {
      id: uuidv4(),
      title: 'Nhẫn kim cương 1 carat - Ảnh chính',
      alt_text: 'Nhẫn kim cương 1 carat cao cấp',
      file_name: 'nhan-kim-cuong-1-carat-1.jpg',
      file_path: '/uploads/products/nhan-kim-cuong-1-carat-1.jpg',
      file_url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
      mime_type: 'image/jpeg',
      file_size: 456789,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-kim-cuong-1-carat'],
      related_type: 'product',
      display_order: 0,
      is_primary: true,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Nhẫn kim cương 1 carat - Chi tiết kim cương',
      alt_text: 'Chi tiết viên kim cương 1 carat',
      file_name: 'nhan-kim-cuong-1-carat-2.jpg',
      file_path: '/uploads/products/nhan-kim-cuong-1-carat-2.jpg',
      file_url: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800',
      mime_type: 'image/jpeg',
      file_size: 389012,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-kim-cuong-1-carat'],
      related_type: 'product',
      display_order: 1,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
    {
      id: uuidv4(),
      title: 'Nhẫn kim cương 1 carat - Góc cạnh',
      alt_text: 'Nhẫn kim cương góc cạnh',
      file_name: 'nhan-kim-cuong-1-carat-3.jpg',
      file_path: '/uploads/products/nhan-kim-cuong-1-carat-3.jpg',
      file_url: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=800',
      mime_type: 'image/jpeg',
      file_size: 412345,
      width: 800,
      height: 800,
      category: 'product',
      related_id: productMap['nhan-kim-cuong-1-carat'],
      related_type: 'product',
      display_order: 2,
      is_primary: false,
      is_active: true,
      created_at: now,
      updated_at: now,
    },
  ];

  await knex('galleries').insert(galleries);
}
