import { Knex } from 'knex';
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex: Knex): Promise<void> {
  // Delete existing data
  await knex('vouchers').del();

  // Insert vouchers
  await knex('vouchers').insert([
    {
      id: uuidv4(),
      code: 'SUMMER2024',
      name: 'Giảm giá mùa hè 2024',
      description: 'Giảm 20% cho tất cả dịch vụ trong mùa hè',
      discount_type: 'percentage',
      discount_value: 20,
      max_discount_amount: 5000000,
      min_order_value: 10000000,
      usage_limit: 100,
      used_count: 15,
      start_date: new Date('2024-06-01'),
      end_date: new Date('2024-08-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'WEDDING2024',
      name: 'Ưu đãi cưới 2024',
      description: 'Giảm 3.000.000đ cho gói cưới trọn gói',
      discount_type: 'fixed',
      discount_value: 3000000,
      max_discount_amount: null,
      min_order_value: 20000000,
      usage_limit: 50,
      used_count: 8,
      start_date: new Date('2024-01-01'),
      end_date: new Date('2024-12-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'NEWYEAR2025',
      name: 'Chào năm mới 2025',
      description: 'Giảm 15% cho đơn hàng đầu tiên',
      discount_type: 'percentage',
      discount_value: 15,
      max_discount_amount: 3000000,
      min_order_value: 5000000,
      usage_limit: 200,
      used_count: 0,
      start_date: new Date('2025-01-01'),
      end_date: new Date('2025-01-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'FLASH50',
      name: 'Flash Sale - Giảm 50%',
      description: 'Giảm 50% cho 100 khách hàng đầu tiên',
      discount_type: 'percentage',
      discount_value: 50,
      max_discount_amount: 10000000,
      min_order_value: 15000000,
      usage_limit: 100,
      used_count: 45,
      start_date: new Date('2024-12-01'),
      end_date: new Date('2024-12-15'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'VIPWEDDING',
      name: 'Gói VIP Wedding',
      description: 'Giảm 5.000.000đ cho gói VIP',
      discount_type: 'fixed',
      discount_value: 5000000,
      max_discount_amount: null,
      min_order_value: 30000000,
      usage_limit: 30,
      used_count: 5,
      start_date: new Date('2024-01-01'),
      end_date: new Date('2025-12-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'EARLYBIRD',
      name: 'Ưu đãi đặt sớm',
      description: 'Giảm 10% khi đặt trước 3 tháng',
      discount_type: 'percentage',
      discount_value: 10,
      max_discount_amount: 2000000,
      min_order_value: 8000000,
      usage_limit: 150,
      used_count: 22,
      start_date: new Date('2024-01-01'),
      end_date: new Date('2025-12-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'FIRSTORDER',
      name: 'Khách hàng mới',
      description: 'Giảm 500.000đ cho đơn hàng đầu tiên',
      discount_type: 'fixed',
      discount_value: 500000,
      max_discount_amount: null,
      min_order_value: 3000000,
      usage_limit: 500,
      used_count: 120,
      start_date: new Date('2024-01-01'),
      end_date: new Date('2025-12-31'),
      is_active: true,
    },
    {
      id: uuidv4(),
      code: 'WEEKEND20',
      name: 'Ưu đãi cuối tuần',
      description: 'Giảm 20% cho đơn hàng cuối tuần',
      discount_type: 'percentage',
      discount_value: 20,
      max_discount_amount: 4000000,
      min_order_value: 7000000,
      usage_limit: 80,
      used_count: 35,
      start_date: new Date('2024-01-01'),
      end_date: new Date('2025-12-31'),
      is_active: true,
    },
  ]);
}
