import { Product } from './types';

export const defaultProducts: Product[] = [
  {
    id: 'wedding-dress',
    name: 'Váy Cưới Cao Cấp',
    price: 15000000,
    currency: 'VNĐ',
    description: 'Váy cưới thiết kế sang trọng, chất liệu cao cấp',
    category: 'Trang phục',
    features: [
      'Thiết kế độc quyền',
      'Chất liệu vải cao cấp nhập khẩu',
      'Đính kết thủ công tinh xảo',
      'May đo theo số đo',
      'Bảo hành 6 tháng',
    ],
    popular: true,
    badge: 'Bán chạy',
    image: 'https://images.unsplash.com/photo-1594552072238-6d4f32f37b8e?w=800',
  },
  {
    id: 'wedding-ring',
    name: 'Nhẫn Cưới Vàng 18K',
    price: 8000000,
    currency: 'VNĐ',
    description: 'Nhẫn cưới vàng 18K đính kim cương',
    category: 'Trang sức',
    features: [
      'Vàng 18K nguyên chất',
      'Kim cương thiên nhiên',
      'Thiết kế tinh tế',
      'Khắc tên miễn phí',
      'Bảo hành trọn đời',
    ],
    badge: 'Cao cấp',
    image: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800',
  },
  {
    id: 'wedding-invitation',
    name: 'Thiệp Cưới Cao Cấp',
    price: 50000,
    currency: 'VNĐ/bộ',
    description: 'Thiệp cưới thiết kế độc đáo, in cao cấp',
    category: 'Thiệp cưới',
    features: [
      'Thiết kế theo yêu cầu',
      'Giấy mỹ thuật cao cấp',
      'In offset chất lượng cao',
      'Phong bì đi kèm',
      'Giao hàng tận nơi',
    ],
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=800',
  },
  {
    id: 'wedding-album',
    name: 'Album Ảnh Cưới',
    price: 3000000,
    currency: 'VNĐ',
    description: 'Album ảnh cưới cao cấp, thiết kế sang trọng',
    category: 'Album ảnh',
    features: [
      'Bìa da cao cấp',
      'In ảnh chất lượng cao',
      'Thiết kế layout chuyên nghiệp',
      '50 trang ảnh',
      'Hộp đựng sang trọng',
    ],
    badge: 'Mới',
    image: 'https://images.unsplash.com/photo-1606800052052-a08af7148866?w=800',
  },
  {
    id: 'wedding-menu-basic',
    name: 'Thực Đơn Tiệc Cưới Cơ Bản',
    price: 350000,
    currency: 'VNĐ/khách',
    description: 'Thực đơn 8 món cho tiệc cưới ấm cúng',
    category: 'Món ăn',
    features: [
      '8 món ăn đa dạng',
      'Nguyên liệu tươi ngon',
      'Đầu bếp chuyên nghiệp',
      'Trang trí món ăn đẹp mắt',
      'Phục vụ tận bàn',
    ],
    image: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800',
  },
  {
    id: 'wedding-menu-premium',
    name: 'Thực Đơn Tiệc Cưới Cao Cấp',
    price: 550000,
    currency: 'VNĐ/khách',
    description: 'Thực đơn 12 món cao cấp với hải sản',
    category: 'Món ăn',
    features: [
      '12 món ăn cao cấp',
      'Hải sản tươi sống',
      'Bếp trưởng 5 sao',
      'Trang trí nghệ thuật',
      'Rượu vang cao cấp',
    ],
    popular: true,
    badge: 'Được yêu thích',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
  },
  {
    id: 'wedding-cake',
    name: 'Bánh Cưới 3 Tầng',
    price: 5000000,
    currency: 'VNĐ',
    description: 'Bánh cưới 3 tầng thiết kế độc đáo',
    category: 'Bánh cưới',
    features: [
      'Thiết kế theo yêu cầu',
      'Kem tươi cao cấp',
      'Trang trí hoa tươi',
      'Phục vụ 100-150 khách',
      'Giao hàng tận nơi',
    ],
    badge: 'Cao cấp',
    image: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=800',
  },
  {
    id: 'wedding-drinks',
    name: 'Gói Đồ Uống Tiệc Cưới',
    price: 80000,
    currency: 'VNĐ/khách',
    description: 'Đồ uống đa dạng cho tiệc cưới',
    category: 'Đồ uống',
    features: [
      'Nước ngọt các loại',
      'Bia tươi',
      'Rượu vang',
      'Nước trái cây tươi',
      'Phục vụ không giới hạn',
    ],
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=800',
  },
];
