import { Package } from './types';

export const defaultPackages: Package[] = [
  {
    id: 'basic',
    name: 'Gói Basic',
    price: 50000000,
    currency: 'VNĐ',
    description: 'Gói cơ bản cho tiệc cưới ấm cúng',
    features: {
      included: [
        'Trang trí sảnh tiệc cơ bản',
        'Backdrop chụp ảnh đơn giản',
        'Âm thanh ánh sáng cơ bản',
        'MC dẫn chương trình',
        'Hỗ trợ setup và dọn dẹp',
        'Tư vấn kế hoạch cơ bản',
      ],
      excluded: ['Makeup artist', 'Chụp ảnh cưới'],
      highlights: ['Trang trí sảnh tiệc', 'MC dẫn chương trình', 'Hỗ trợ setup'],
    },
    images: [],
    badge: 'Phổ biến',
  },
  {
    id: 'premium',
    name: 'Gói Premium',
    price: 100000000,
    currency: 'VNĐ',
    description: 'Gói cao cấp với nhiều dịch vụ hơn',
    popular: true,
    features: {
      included: [
        'Trang trí sảnh tiệc cao cấp',
        'Backdrop & Photobooth chuyên nghiệp',
        'Âm thanh ánh sáng hiện đại',
        'MC & Ban nhạc',
        'Trang điểm cô dâu chú rể',
        'Chụp ảnh phóng sự (300+ ảnh)',
        'Quay phim Full HD',
        'Wedding Planner chuyên nghiệp',
        'Xe hoa trang trí',
      ],
      excluded: ['Flycam', 'Thiệp cưới'],
      highlights: ['Wedding Planner', 'Chụp ảnh 300+', 'Quay phim Full HD'],
    },
    images: [],
    badge: 'Được yêu thích nhất',
  },
  {
    id: 'luxury',
    name: 'Gói Luxury',
    price: 200000000,
    currency: 'VNĐ',
    description: 'Gói sang trọng cho tiệc cưới hoàn hảo',
    features: {
      included: [
        'Trang trí sảnh tiệc sang trọng',
        'Backdrop & Photobooth cao cấp',
        'Hệ thống âm thanh ánh sáng 5 sao',
        'MC chuyên nghiệp & Ban nhạc live',
        'Trang điểm cô dâu chú rể & gia đình',
        'Chụp ảnh phóng sự (500+ ảnh)',
        'Quay phim 4K + Flycam',
        'Wedding Planner VIP',
        'Xe hoa sang trọng',
        'Thiệp cưới thiết kế riêng',
        'Quà tặng khách mời',
        'Dịch vụ lưu trú cho khách VIP',
      ],
      excluded: [],
      highlights: ['Quay phim 4K + Flycam', 'Wedding Planner VIP', 'Chụp ảnh 500+'],
    },
    images: [],
    badge: 'Cao cấp nhất',
  },
];
